FROM node:14.5.0-alpine
FROM openjdk:7

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-compiler-generator-service

WORKDIR /data/freelog-compiler-generator-service

COPY . /data/freelog-compiler-generator-service

RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 7727
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 7727

ENTRYPOINT ["java" "-jar", "./freelog-compiler-generator.jar"]
CMD [ "npm", "start" ]
