FROM openjdk:14.0.2

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-compiler-generator-service

WORKDIR /data/freelog-compiler-generator-service

COPY . /data/freelog-compiler-generator-service

RUN apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
  && apt-get install -y nodejs \
  && curl -L https://www.npmjs.com/install.sh | sh

RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 7727
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 7727

CMD [ "npm", "start" ]
